// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/update/update.proto

package update

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_IDLE        Status = 1
	Status_STATUS_RUNNING     Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_IDLE",
		2: "STATUS_RUNNING",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_IDLE":        1,
		"STATUS_RUNNING":     2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_update_update_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_update_update_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_update_update_proto_rawDescGZIP(), []int{0}
}

type StatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordsTotal    int64                  `protobuf:"varint,1,opt,name=words_total,json=wordsTotal,proto3" json:"words_total,omitempty"`
	WordsUnique   int64                  `protobuf:"varint,2,opt,name=words_unique,json=wordsUnique,proto3" json:"words_unique,omitempty"`
	ComicsTotal   int64                  `protobuf:"varint,3,opt,name=comics_total,json=comicsTotal,proto3" json:"comics_total,omitempty"`
	ComicsFetched int64                  `protobuf:"varint,4,opt,name=comics_fetched,json=comicsFetched,proto3" json:"comics_fetched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsReply) Reset() {
	*x = StatsReply{}
	mi := &file_proto_update_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReply) ProtoMessage() {}

func (x *StatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_update_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReply.ProtoReflect.Descriptor instead.
func (*StatsReply) Descriptor() ([]byte, []int) {
	return file_proto_update_update_proto_rawDescGZIP(), []int{0}
}

func (x *StatsReply) GetWordsTotal() int64 {
	if x != nil {
		return x.WordsTotal
	}
	return 0
}

func (x *StatsReply) GetWordsUnique() int64 {
	if x != nil {
		return x.WordsUnique
	}
	return 0
}

func (x *StatsReply) GetComicsTotal() int64 {
	if x != nil {
		return x.ComicsTotal
	}
	return 0
}

func (x *StatsReply) GetComicsFetched() int64 {
	if x != nil {
		return x.ComicsFetched
	}
	return 0
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=update.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_proto_update_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_update_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_proto_update_update_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReply) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

var File_proto_update_update_proto protoreflect.FileDescriptor

const file_proto_update_update_proto_rawDesc = "" +
	"\n" +
	"\x19proto/update/update.proto\x12\x06update\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x01\n" +
	"\n" +
	"StatsReply\x12\x1f\n" +
	"\vwords_total\x18\x01 \x01(\x03R\n" +
	"wordsTotal\x12!\n" +
	"\fwords_unique\x18\x02 \x01(\x03R\vwordsUnique\x12!\n" +
	"\fcomics_total\x18\x03 \x01(\x03R\vcomicsTotal\x12%\n" +
	"\x0ecomics_fetched\x18\x04 \x01(\x03R\rcomicsFetched\"5\n" +
	"\vStatusReply\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.update.StatusR\x06status*E\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATUS_IDLE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x022\xa8\x02\n" +
	"\x06Update\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x13.update.StatusReply\"\x00\x12:\n" +
	"\x06Update\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x125\n" +
	"\x05Stats\x12\x16.google.protobuf.Empty\x1a\x12.update.StatsReply\"\x00\x128\n" +
	"\x04Drop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B\x1fZ\x1dyadro.com/course/proto/updateb\x06proto3"

var (
	file_proto_update_update_proto_rawDescOnce sync.Once
	file_proto_update_update_proto_rawDescData []byte
)

func file_proto_update_update_proto_rawDescGZIP() []byte {
	file_proto_update_update_proto_rawDescOnce.Do(func() {
		file_proto_update_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_update_update_proto_rawDesc), len(file_proto_update_update_proto_rawDesc)))
	})
	return file_proto_update_update_proto_rawDescData
}

var file_proto_update_update_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_update_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_update_update_proto_goTypes = []any{
	(Status)(0),           // 0: update.Status
	(*StatsReply)(nil),    // 1: update.StatsReply
	(*StatusReply)(nil),   // 2: update.StatusReply
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_proto_update_update_proto_depIdxs = []int32{
	0, // 0: update.StatusReply.status:type_name -> update.Status
	3, // 1: update.Update.Ping:input_type -> google.protobuf.Empty
	3, // 2: update.Update.Status:input_type -> google.protobuf.Empty
	3, // 3: update.Update.Update:input_type -> google.protobuf.Empty
	3, // 4: update.Update.Stats:input_type -> google.protobuf.Empty
	3, // 5: update.Update.Drop:input_type -> google.protobuf.Empty
	3, // 6: update.Update.Ping:output_type -> google.protobuf.Empty
	2, // 7: update.Update.Status:output_type -> update.StatusReply
	3, // 8: update.Update.Update:output_type -> google.protobuf.Empty
	1, // 9: update.Update.Stats:output_type -> update.StatsReply
	3, // 10: update.Update.Drop:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_update_update_proto_init() }
func file_proto_update_update_proto_init() {
	if File_proto_update_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_update_update_proto_rawDesc), len(file_proto_update_update_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_update_update_proto_goTypes,
		DependencyIndexes: file_proto_update_update_proto_depIdxs,
		EnumInfos:         file_proto_update_update_proto_enumTypes,
		MessageInfos:      file_proto_update_update_proto_msgTypes,
	}.Build()
	File_proto_update_update_proto = out.File
	file_proto_update_update_proto_goTypes = nil
	file_proto_update_update_proto_depIdxs = nil
}
